"""Local filesystem storage for development and single-node deployments."""

from __future__ import annotations

import logging
import re
from functools import lru_cache
from pathlib import Path

from app.core.config import get_settings
from app.core.errors import NotFoundError

logger = logging.getLogger(__name__)

# Keys are generated by the application (uuid-based), so this is a belt-and-braces
# assertion rather than sanitisation of hostile input: anything that could escape
# the root is rejected outright instead of being cleaned up and used.
_SAFE_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9/_.-]{0,240}$")


class LocalDiskStorage:
    def __init__(self, root: str | Path) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        if not _SAFE_KEY.match(key) or ".." in key:
            raise ValueError(f"Unsafe storage key: {key!r}")
        path = (self._root / key).resolve()
        # Even with the regex, confirm the resolved path is inside the root.
        # Symlinks and normalisation are exactly where path traversal survives
        # a naive string check.
        if not path.is_relative_to(self._root):
            raise ValueError(f"Storage key escapes root: {key!r}")
        return path

    def put(self, key: str, data: bytes, *, content_type: str | None = None) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a temp file then rename: rename is atomic on POSIX, so a
        # crash mid-write leaves no half-written object for a reader to find.
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_bytes(data)
        tmp.replace(path)

    def get(self, key: str) -> bytes:
        path = self._path(key)
        if not path.is_file():
            raise NotFoundError("Stored object not found.")
        return path.read_bytes()

    def delete(self, key: str) -> None:
        path = self._path(key)
        path.unlink(missing_ok=True)

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()


@lru_cache
def get_storage():
    """Resolve the configured backend once per process."""
    settings = get_settings()
    if settings.storage_backend == "local":
        return LocalDiskStorage(settings.storage_local_path)
    if settings.storage_backend == "postgres":
        from app.providers.storage.postgres_store import PostgresStorage

        return PostgresStorage()
    # S3 lives behind the same protocol; not wired in this build because the
    # local backend is what the demo and the test suite exercise. Adding it is
    # one module implementing StorageBackend (§29.1).
    raise NotImplementedError(
        f"Storage backend {settings.storage_backend!r} is not available in this build."
    )
