"""Postgres-backed object storage.

**Why this exists.** The API writes an uploaded file and the worker reads it back
to parse — so the two processes need shared storage. On a local disk that is a
mounted volume, but most container platforms (Railway among them) attach a volume
to exactly one service. The alternatives were to collapse the API and the worker
into one process, abandoning the asynchronous ingestion the architecture is built
on (D6), or to add an S3 vendor.

Storing the bytes in Postgres is shared by construction, transactional with the
document row, needs no additional service, and requires no new credentials.

**What it costs.** Database size and WAL volume. Large files in a relational
database are a well-known way to make backups slow and expensive, so this is the
right answer at demo and small-team scale and the wrong one at corpus scale —
which is exactly why `StorageBackend` is a protocol. `S3Storage` is the next
implementation, and swapping is one module and one environment variable
(TDD §29.1).

`bytea` rather than a large object: large objects live outside the table, are not
covered by the same MVCC rules, and leak unless explicitly unlinked. A `bytea`
column is deleted when its row is.
"""

from __future__ import annotations

import logging

from sqlalchemy import text

from app.core.errors import NotFoundError
from app.db.session import SessionLocal

logger = logging.getLogger(__name__)


class PostgresStorage:
    """Objects in a table. Keys are generated by the application, never user input."""

    def put(self, key: str, data: bytes, *, content_type: str | None = None) -> None:
        # Its own short-lived session: storage writes must not be entangled with
        # whatever transaction the caller happens to have open, and must not be
        # rolled back by an unrelated failure later in that transaction.
        with SessionLocal() as session:
            session.execute(
                text(
                    """
                    INSERT INTO stored_objects (key, content, content_type, byte_size)
                    VALUES (:key, :content, :content_type, :byte_size)
                    ON CONFLICT (key) DO UPDATE
                        SET content = EXCLUDED.content,
                            content_type = EXCLUDED.content_type,
                            byte_size = EXCLUDED.byte_size
                    """
                ),
                {
                    "key": key,
                    "content": data,
                    "content_type": content_type,
                    "byte_size": len(data),
                },
            )
            session.commit()

    def get(self, key: str) -> bytes:
        with SessionLocal() as session:
            row = session.execute(
                text("SELECT content FROM stored_objects WHERE key = :key"),
                {"key": key},
            ).first()
        if row is None:
            raise NotFoundError("Stored object not found.")
        return bytes(row[0])

    def delete(self, key: str) -> None:
        with SessionLocal() as session:
            session.execute(text("DELETE FROM stored_objects WHERE key = :key"), {"key": key})
            session.commit()

    def exists(self, key: str) -> bool:
        with SessionLocal() as session:
            row = session.execute(
                text("SELECT 1 FROM stored_objects WHERE key = :key"), {"key": key}
            ).first()
        return row is not None
